### ISSUE TITLE
A better way to skip objects/methods/interfaces

### ISSUE THREAD

**Issue by evverx** [matusmarhefka/dfuzzer#70]
It was discussed in https://github.com/matusmarhefka/dfuzzer/pull/65#discussion_r864277060

**Comment by mrc0mmand** [comment]
I wonder if we should make it backwards-compatible, i.e. keep the `method_string description` format, where the `method_string` would be, for example, a colon-separated list (since colon is not a valid character for an object/interface/method name):

```
[org.freedesktop.systemd1]
/org/freedesktop/systemd1:org.freedesktop.systemd1.Manager:Reload destructive
```
since by parsing the method string backwards and treating the missing/empty parts as "any" we would still make `Reload destructive` a valid suppression string.

Or if we should change the format completely (not sure how, yet, though).
